### PR TITLE
Joss review response

### PR DESCRIPTION
**Pull request by nbwuzhe**
This PR is for responding to the review comments of the manuscript to JOSS.

### CODE REVIEW

**Comment by nbwuzhe** [comment]
Hi @felixhorger, thanks for reviewing our manuscript to JOSS. I have changed README.md to address both of your comments here. Would also appreciate input from the other authors.

**Comment by alexjaffray** [comment]
daa16087ed34c54801226b02b2bc95e0ff3d06ee addresses #11

**Comment by alexjaffray** [comment]
06c5e819b5fddbe6e93d052de05cfdbe725226fe, aff10d5235f9d2e5b91688436dfba3dccc7dc66d, e81f4e4c5252fdf709301757c6697e049ea5c8fc fix #6, #5, and #8 respectively

**Comment by alexjaffray** [comment]
Renamed variables, holding off on renaming the functions just yet @nbwuzhe @mrikasper

**Comment by alexjaffray** [comment]
List of functions needing automated tests: 

- [ ] getSliceOrder
- [ ] syncTrajAndData!
- [ ] do_k0_correction!
- [ ] adjustHeader!
- [ ] checkAcquisitionNodes!
- [ ] validateSiemensMRD!
- [ ] validateAcqData!
- [ ] preprocessCartesianData
- [ ] removeOversampling!
- [ ] mergeRawInterleaves
- [ ] applyGIRF!
- [ ] applyK0!
- [ ] saveMap
- [ ] loadMap
- [ ] shift_kspace!

**Comment by alexjaffray** [comment]
10761b8ebc68990ccd296c96b29b037489bbeed3 addresses #10

**Comment by alexjaffray** [comment]
> List of functions needing automated tests:
> 
> * [ ]  getSliceOrder
> * [ ]  syncTrajAndData!
> * [ ]  do_k0_correction!
> * [ ]  adjustHeader!
> * [ ]  checkAcquisitionNodes!
> * [ ]  validateSiemensMRD!
> * [ ]  validateAcqData!
> * [ ]  preprocessCartesianData
> * [ ]  removeOversampling!
> * [ ]  mergeRawInterleaves
> * [ ]  applyGIRF!
> * [ ]  applyK0!
> * [ ]  saveMap
> * [ ]  loadMap
> * [ ]  shift_kspace!

Need to update for new function names

**Comment by alexjaffray** [comment]
Updated function list to track test writing progress: 

Utilities:
- [x]     calculate_b0_maps - Alex
- [x]     get_slice_order - Tim
- [x]     sync_traj_and_data! - Alex
- [x]     do_k0_correction! - Alex
- [x]     adjust_header! - Tim
- [x]     check_acquisition_nodes! - Alex
- [x]     validate_siemens_mrd! - Alex
- [x]     validate_acq_data! - Alex
- [x]     preprocess_cartesian_data -Alex
- [x]     remove_oversampling! - Lars
- [x]     save_map - Tim
- [x]     load_map - Tim
- [x]     shift_kspace! - Alex 

Integration Tests:
- [x]     merge_raw_interleaves - Tim and Alex and Lars
- [x]     apply_girf! - Alex
- [x]     apply_k0! - Alex

**Review by alexjaffray — APPROVED** [review]
Significant progress towards revision response, approving to finalize doc testing and release soon

**Pull request merged**
